#数据库的连接
spring:
  application:
    name: tlias-web-managemen
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: abc123

  mybatis:
   configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
